feat: some updates

diff --git a/.devcontainer/docker/Dockerfile b/.devcontainer/docker/Dockerfile
--- a/.devcontainer/docker/Dockerfile
+++ b/.devcontainer/docker/Dockerfile
@@ -2,6 +2,7 @@
 ARG IMAGE_NAME=ubuntu
 ARG VARIANT=${VARIANT:-latest}
 ARG BASE_IMAGE=${IMAGE_NAME}:${VARIANT}
+ARG DEV_PARENT_IMAGE=devuser
 FROM ${BASE_IMAGE} AS builder
 
 # Build arguments need to be re-declared if used in FROM instructions
@@ -10,12 +11,15 @@ ARG BASE_IMAGE
 ARG IMAGE_NAME
 ARG VARIANT
 
+ARG DEV_PARENT_IMAGE
+
 ARG PASSGEN=/passgen.sh
 ARG LOGGER=/logger.sh
 ARG FIXPATH=/fixpath.sh
 ARG TIMEZONE=UTC
 
 # Timezone and locale settings
+# ? localedef -i en_US -f UTF-8 en_US.UTF-8
 ENV TZ=$TIMEZONE
 ENV LANG=C.UTF-8
 ENV LC_ALL=C.UTF-8
@@ -34,18 +38,19 @@ ENV CODESERVER_PASS_CHARSET=$DEFAULT_PASS_CHARSET
 ENV DEBIAN_FRONTEND=noninteractive
 
 # Copy library scripts
-COPY --chmod=755 .devcontainer/docker/lib-scripts/*.sh /tmp/lib-scripts/
+COPY --chmod=755 .devcontainer/docker/lib-scripts/builder-*.sh /tmp/lib-scripts/
 
 USER root
 
 # Update and install essential packages
-RUN sed -i "s|\$LOGGER|$LOGGER|g" /tmp/lib-scripts/*.sh \
+RUN sed -i "s|\$LOGGER|$LOGGER|g" /tmp/lib-scripts/builder-generators.sh \
   && /tmp/lib-scripts/builder-generators.sh \
   && /tmp/lib-scripts/builder-utils.sh \
   # Cleanup
   && apt-get clean -y \
+  && apt-get -y autoremove \
   && rm -rf /var/lib/apt/lists/* \
-  # && rm -rf /tmp/lib-scripts/builder-*.sh \
+  && rm -rf /tmp/lib-scripts \
   # Set timezone
   && [ "$TIMEZONE" = "UTC" ] || \
   ln -sf /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
@@ -68,7 +73,63 @@ RUN if [ "$IMAGE_NAME" = "ubuntu" ]; then \
 # --------------------------------------------------------------
 
 
-FROM builder AS devuser
+# --------------------------------------------------------------
+# Build-only builder stages: brewbuilder, gobuilder
+# --------------------------------------------------------------
+FROM builder AS brewbuilder
+
+ARG USERNAME=vscode
+ARG USER_UID=1000
+ARG USER_GID=$USER_UID
+
+# Copy library scripts
+COPY --chmod=755 .devcontainer/docker/lib-scripts/git-install.sh /tmp/lib-scripts/
+
+USER root
+
+RUN apt-get update \
+  && apt-get -y install --no-install-recommends sudo \
+  && groupadd --gid "$USER_GID" "$USERNAME" \
+  && useradd --uid "$USER_UID" --gid "$USER_GID" -m "$USERNAME" -s /bin/bash \
+  && echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > "/etc/sudoers.d/$USERNAME" \
+  && chmod 0440 "/etc/sudoers.d/$USERNAME" \
+  && /tmp/lib-scripts/git-install.sh \
+  # Cleanup
+  && apt-get clean -y \
+  && rm -rf /var/lib/apt/lists/*
+
+USER $USERNAME
+
+RUN NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+
+CMD ["/bin/bash"]
+
+
+FROM builder AS gobuilder
+
+ARG USERNAME=vscode
+ARG USER_UID=1000
+ARG USER_GID=$USER_UID
+
+# Copy library scripts
+COPY --chmod=755 .devcontainer/docker/lib-scripts/go-install.sh /tmp/lib-scripts/
+
+USER root
+
+RUN /tmp/lib-scripts/go-install.sh \
+  # Cleanup
+  && apt-get clean -y \
+  && rm -rf /var/lib/apt/lists/* \
+  && rm -rf /tmp/lib-scripts
+CMD ["/bin/bash"]
+
+# --------------------------------------------------------------
+
+
+# --------------------------------------------------------------
+# Intermediary builder stages: devbuilder, devuser, brewuser
+# --------------------------------------------------------------
+FROM builder AS devbuilder
 
 # Create a non-root user
 ARG USERNAME=devcontainer
@@ -99,32 +160,45 @@ ENV PYTHON_VERSION=$PYTHON_VERSION
 # Update PATH here so that all shells contain the updated PATH
 ENV PATH="/home/$USERNAME/.local/bin:${PATH}"
 
-RUN /tmp/lib-scripts/devuser-generators.sh \
-  && /tmp/lib-scripts/devuser-utils.sh \
+# Copy library scripts
+COPY --chmod=755 .devcontainer/docker/lib-scripts/devbuilder*.sh /tmp/lib-scripts/
+COPY --chmod=755 .devcontainer/docker/lib-scripts/git-install.sh /tmp/lib-scripts/
+
+RUN /tmp/lib-scripts/devbuilder-generators.sh \
+  && /tmp/lib-scripts/devbuilder-utils.sh \
   && /tmp/lib-scripts/git-install.sh \
-  && /tmp/lib-scripts/devuser-setup.sh \
+  && /tmp/lib-scripts/devbuilder-user-setup.sh \
   # Cleanup
   && apt-get clean -y \
   && apt-get -y autoremove \
   && rm -rf /var/lib/apt/lists/* \
-  && rm -f /tmp/lib-scripts/devuser-*.sh \
-  && rm -f /tmp/lib-scripts/git-install.sh
+  && rm -rf /tmp/lib-scripts
 
 # Install Homebrew for the non-root user
 # Note: Homebrew on Linux doesn't require admin privileges when installed in home directory
 USER $USERNAME
 WORKDIR /home/$USERNAME
 
-# Package management control
-# Whether to install Homebrew
-# (Very large and has a non-fixable high cve (as of January 2026); install only if needed)
-ARG HOMEBREW_ENABLED=false
-ARG NO_BREW_UPDATE=$DEV
-RUN test "$HOMEBREW_ENABLED" != "true" \
-  || NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
-
-# Set default command
 CMD ["/bin/bash"]
+
+
+FROM devbuilder AS devuser
+
+USER $USERNAME
+WORKDIR /home/$USERNAME
+
+CMD ["/bin/bash"]
+
+
+FROM devbuilder AS brewuser
+
+WORKDIR /home/linuxbrew
+COPY --from=brewbuilder --chown=$USERNAME:$USERNAME /home/linuxbrew .
+
+USER $USERNAME
+WORKDIR /home/$USERNAME
+
+CMD ["sh", "-c", "exec $BREW"]
 
 # --------------------------------------------------------------
 
@@ -132,47 +206,50 @@ CMD ["/bin/bash"]
 # --------------------------------------------------------------
 # THIS IS THE base `devcontainer` TARGET
 # --------------------------------------------------------------
-FROM devuser AS base
-
-# Whether to install shfmt (shell script formatter) system-wide
-# (has many CVEs in the Go toolchain; install only if needed)
-ARG SHFMT_ENABLED=false
+FROM $DEV_PARENT_IMAGE AS base
 
 # Default user workspace directory
 ARG DEFAULT_WORKSPACE=/home/$USERNAME/workspace
 ENV DEFAULT_WORKSPACE=$DEFAULT_WORKSPACE
 
+ARG PRE_COMMIT_ENABLED=false
+
 # Set default to not reset root password, in case devcontainer inherits from devtools or cloudtools
 # Precautionary measure to avoid interactive prompt when running devcontainer
 ENV RESET_ROOT_PASS=false
 
+# Copy library scripts
+COPY --chmod=755 .devcontainer/docker/lib-scripts/base-*.sh /tmp/lib-scripts/
 # Copy post-start script
 COPY --chmod=755 .devcontainer/docker/utils/post-start.sh /usr/local/bin/post-start
+
+# Copy shfmt installation from gobuilder stage
+COPY --from=gobuilder /usr/local/bin/shfmt /usr/local/bin/shfmt
 
 USER root
 
 RUN sed -i "s|\$LOGGER|$LOGGER|g" /usr/local/bin/post-start \
-  & /tmp/lib-scripts/base-utils.sh \
+  && /tmp/lib-scripts/base-utils.sh \
   # Cleanup
   && apt-get clean -y \
   && rm -rf /var/lib/apt/lists/* \
-  && rm -f /tmp/lib-scripts/base-*.sh
+  && rm -rf /tmp/lib-scripts
 
 # Switch to non-root user
 USER $USERNAME
 WORKDIR $DEFAULT_WORKSPACE
 
-# Whether to install pre-commit via Homebrew
-# (will result in Homebrew installing Python dependencies)
-ARG PRE_COMMIT_ENABLED=false
 # If pipx is installed, it implies a user-managed Python environment; use it to install pre-commit
-# Otherwise, install as a feature via devcontainer.json
-# Use flag (build-arg) to install pre-commit with Homebrew to keep base image size down (Homebrew will install Python dependencies)
-RUN if $PIPX 2>/dev/null; then \
-    $($PIPX) install pre-commit; \
-  else \
-    test "$PRE_COMMIT_ENABLED" != "true" \
-      || { test "$HOMEBREW_ENABLED" != "true" || $BREW install pre-commit; }; \
+# Otherwise, use Homebrew to install pre-commit if Homebrew is available
+# Install as a feature via devcontainer.json if neither pipx nor Homebrew is available
+RUN if ! type pre-commit >/dev/null 2>&1 && [ "$PRE_COMMIT_ENABLED" = "true" ]; then \
+    if "$PIPX" >/dev/null 2>&1; then \
+      $("$PIPX") install pre-commit; \
+    else \
+      if type "$BREW" > /dev/null 2>&1 ; then \
+        "$BREW" install pre-commit; \
+      fi; \
+    fi; \
   fi
 
 LABEL org.opencontainers.image.ref.name="<repo-name>:devcontainer-$BASE_IMAGE"
@@ -192,46 +269,48 @@ ENV RESET_ROOT_PASS=$DEFAULT_ROOT_PASS
 # Needed to properly reference target version of python3
 # ENV PATH="/home/linuxbrew/.linuxbrew/opt/python3/bin:${PATH}"
 
+# Copy library scripts
+COPY --chmod=755 .devcontainer/docker/lib-scripts/devtools-*.sh /tmp/lib-scripts/
+COPY --chmod=755 .devcontainer/docker/lib-scripts/python-install.sh /tmp/lib-scripts/
+
 USER root
 
 RUN /tmp/lib-scripts/devtools-utils.sh \
+  && /tmp/lib-scripts/python-install.sh \
   # Cleanup
   && apt-get clean -y \
   && rm -rf /var/lib/apt/lists/* \
-  && rm -f /tmp/lib-scripts/devtools-*.sh
+  && rm -rf /tmp/lib-scripts
 
 # Switch to non-root user
 USER $USERNAME
 
-# Install Python, pipx, Poetry, uv, and other dev tools via Homebrew.
+# Install Python, pipx, Poetry, uv, and other dev tools.
 # Do nothing if PYTHON_VERSION is 'devcontainer' or matches the USERNAME.
 # USERNAME cannot be 'system' or 'latest'.
-RUN if  [ "$HOMEBREW_ENABLED" = "true" ]; then \
-    test "$NO_BREW_UPDATE" = "true" || $BREW update \
+ARG NO_BREW_UPDATE=$DEV
+RUN if type "$BREW" > /dev/null 2>&1; then \
+    test "$NO_BREW_UPDATE" = "true" || "$BREW" update \
     && if [ "$PYTHON_VERSION" = "latest" ] ; then \
-      $BREW install python3; \
+      "$BREW" install python3; \
     elif [ "$PYTHON_VERSION" != "devcontainer" ] && [ "$PYTHON_VERSION" != "system" ] \
       && [ "$PYTHON_VERSION" != "$USERNAME" ] \
       && [ "$(python3 --version | awk -F. '{print $1"."$2}')" != "Python ${PYTHON_VERSION}" ] ; then \
-      $BREW install python@${PYTHON_VERSION}; \
+      "$BREW" install "python@${PYTHON_VERSION}"; \
     fi \
-    # Install pipx after Python
     && if [ "$PYTHON_VERSION" != "system" ] ; then \
-      # Homebrew installs the latest version of Python if Python not already installed (by Homebrew)
-      $BREW install pipx; \
-    fi \
-    # Configure pipx, and install Poetry and uv after ensuring pipx is installed
-    && if $PIPX 2>/dev/null; then \
-      $($PIPX) install \
-        pre-commit \
-        poetry \
-        uv; \
-      fi; \
-  else \
-    if [ "$PYTHON_VERSION" = "latest" ] \
-      && $PIPX 2> /dev/null; then \
-        $($PIPX) install pip; \
+      "$BREW" install pipx; \
     fi; \
+  else \
+    if [ "$PYTHON_VERSION" = "latest" ] && "$PIPX" 2> /dev/null \
+      && [ "$IMAGE_NAME" = "ubuntu" ]; then \
+        $("$PIPX") install pip; \
+    fi; \
+  fi \
+  && if "$PIPX" 2>/dev/null; then \
+    type pre-commit >/dev/null 2>&1 || $("$PIPX") install pre-commit \
+    && $("$PIPX") install poetry \
+    && $("$PIPX") install uv; \
   fi
 
 USER root
@@ -240,7 +319,6 @@ USER $USERNAME
 
 ENTRYPOINT ["/docker-entrypoint.sh"]
 
-# Set default command
 CMD ["/bin/bash"]
 
 # --------------------------------------------------------------
@@ -252,13 +330,16 @@ FROM base AS cloudtools
 # ? https://github.com/awslabs/aws-terraform-dev-container/blob/main/.devcontainer/library-scripts/cloud-cli-tools.sh
 # ? https://github.com/awslabs/aws-terraform-dev-container/blob/main/.devcontainer/library-scripts/terraform-tools.sh
 
+# Copy library scripts
+COPY --chmod=755 .devcontainer/docker/lib-scripts/cloud*tools.sh /tmp/lib-scripts/
+
 USER root
 
 RUN /tmp/lib-scripts/cloud-cli-tools.sh \
   # Cleanup
   && apt-get clean -y \
   && rm -rf /var/lib/apt/lists/* \
-  && rm -f /tmp/lib-scripts/cloud*tools.sh
+  && rm -rf /tmp/lib-scripts
 
 USER $USERNAME
 
@@ -280,17 +361,27 @@ ENV CODE_SERVER_WORKSPACE=$DEFAULT_WORKSPACE
 ENV CODE_SERVER_CONFIG=/home/$USERNAME/.config/code-server/config.yaml
 ENV CODE_SERVER_EXTENSIONS=$DEFAULT_WORKSPACE/.code-server/extensions/extensions.json
 
+# Copy library scripts
+COPY --chmod=755 .devcontainer/docker/lib-scripts/codeserver-*.sh /tmp/lib-scripts/
+# Copy start-code-server script
 COPY --chmod=755 .devcontainer/docker/utils/start-code-server.sh /usr/local/bin/start-code-server
 
 USER root
 
-RUN /tmp/lib-scripts/codeserver-utils.sh
-
-USER $USERNAME
+RUN /tmp/lib-scripts/codeserver-utils.sh \
+  # Remove sudo access for non-root user
+  && rm -f /etc/sudoers.d/$USERNAME \
+  && SUDO_FORCE_REMOVE=yes apt-get -y remove sudo \
+  # Cleanup
+  && apt-get clean -y \
+  && rm -rf /var/lib/apt/lists/* \
+  && rm -rf /tmp/lib-scripts
 
 RUN $LOGGER "Installing code-server..." \
   && curl -fsSL https://code-server.dev/install.sh | sh \
   && $LOGGER "code-server installation complete."
+
+USER $USERNAME
 
 EXPOSE 8080
 
@@ -320,17 +411,27 @@ ENV CODE_SERVER_WORKSPACE=$DEFAULT_WORKSPACE
 ENV CODE_SERVER_CONFIG=/home/$USERNAME/.config/code-server/config.yaml
 ENV CODE_SERVER_EXTENSIONS=$DEFAULT_WORKSPACE/.code-server/extensions/extensions.json
 
+# Copy library scripts
+COPY --chmod=755 .devcontainer/docker/lib-scripts/codeserver-*.sh /tmp/lib-scripts/
+# Copy start-code-server script
 COPY --chmod=755 .devcontainer/docker/utils/start-code-server.sh /usr/local/bin/start-code-server
 
 USER root
 
-RUN /tmp/lib-scripts/codeserver-utils.sh
-
-USER $USERNAME
+RUN /tmp/lib-scripts/codeserver-utils.sh \
+  # Remove sudo access for non-root user
+  && rm -f /etc/sudoers.d/$USERNAME \
+  && SUDO_FORCE_REMOVE=yes apt-get -y remove sudo \
+  # Cleanup
+  && apt-get clean -y \
+  && rm -rf /var/lib/apt/lists/* \
+  && rm -rf /tmp/lib-scripts
 
 RUN $LOGGER "Installing code-server..." \
   && curl -fsSL https://code-server.dev/install.sh | sh \
   && $LOGGER "code-server installation complete."
+
+USER $USERNAME
 
 EXPOSE 8080
 
@@ -354,8 +455,7 @@ FROM builder AS production
 RUN apt-get update \
   && apt-get -y install --no-install-recommends tini \
   && apt-get clean -y \
-  && rm -rf /var/lib/apt/lists/* \
-  && rm -rf /tmp/lib-scripts/
+  && rm -rf /var/lib/apt/lists/*
 
 ENTRYPOINT ["/usr/bin/tini", "--"]
 
